### ISSUE TITLE
does the PWC week-113 challenge-2 lua code do what's intended?

### ISSUE THREAD

**Issue by stuart-little** [Abigail/Abigail.github.io#1]
I've been getting into `lua` myself, and out of curiosity, have been perusing people's solutions. For [week 113 challenge 2](https://theweeklychallenge.org/blog/perl-weekly-challenge-113/#TASK2) your `lua` version [reads](https://github.com/manwar/perlweeklychallenge-club/blob/master/challenge-113/abigail/lua/ch-2.lua)
```
for line in io . lines () do
    local sum = 0
    for  n in line : gmatch ("-?[0-9]+")
    do   sum = sum + tonumber (n)
    end
    local c = 0
    for  n in line : gmatch ("-?[0-9]+")
    do   if   c > 0
         then io . write (" ")
         end
         c = c + 1
         io . write (sum - tonumber (n))
    end
    io . write ("\n")
end
```
That doesn't seem to me to do what's intended: it's supposed to subtract each number from the *total* tree sum, but when run on an input file containing
```
        1
       / \
      2   3
     /   / \
    4   5   6
     \
      7
```
it returns
```
0

3 2

11 10 9

0
```
which is clearly wrong (it's also the [original example](https://theweeklychallenge.org/blog/perl-weekly-challenge-113/#TASK2)).

It looks to me like what's happening there is that a new sum is computed for each row of the tree, because you declare your `sum` variable as `local`, once per loop iteration.

Am I misreading this?

**Comment by Abigail** [comment]
You are not misreading this; this is exactly what it does.

My programs typically treat each line of input as a *different* test case.

I'm usually too lazy to copy comments, but I mention this in my Perl solution (and also in the blog post I made about this challenge). I decided to ignore the "binary tree" aspect of the problem for two reasons: first, it's completely irrelevant whether the numbers are placed in a tree, or a list, or perhaps a square or triangle. Second (and more importantly), the challenge is utterly unclear how it will represent a tree in general. The example has been carefully crafted to just work, but even adding a second child under the 2 becomes problematic. So my program assumes all numbers to be on a single line, and each subsequent line is treated as a different tree.

**Comment by stuart-little** [comment]
Ah, I see, thanks! 

I agree these tree challenges are a nuisance :): input is always an issue, and output is too, if you want to draw the thing.

I did see your post, but part of what got me here was that it wouldn't have been much of a change to make `sum` a global variable, so even as a protest against the challenge format/setup, that seemed gratuitous :)..
